-- Recharj — seed 001: sources
-- Run after migrations/002_courses_sources.sql and 014_course_source_i18n.sql.
-- 34 sources, one row per study/technique. Generated via generate-sources-seed.mjs, review before executing.
-- Fixed UUIDs (a0000000-...-0001 .. 0034 = S01..S34) so 002_courses.sql can
-- reference them directly without a lookup step.

insert into sources (id, short_label, short_label_en, study_title, study_title_en, authors, authors_en, year, journal_or_publisher, journal_or_publisher_en, summary, summary_en, external_url, is_scientific) values

('a0000000-0000-0000-0000-000000000001', $$Boothby et al., 2018$$, $$Boothby et al., 2018$$, $$The Liking Gap in Conversations: Do People Like Us More Than We Think?$$, $$The Liking Gap in Conversations: Do People Like Us More Than We Think?$$, $$Boothby, E., Cooney, G., Clark, M. S., & Epley, N.$$, $$Boothby, E., Cooney, G., Clark, M. S., & Epley, N.$$, 2018, $$Psychological Science$$, $$Psychological Science$$, $$Les chercheurs ont fait discuter des inconnus par paires, pendant quelques minutes à plusieurs semaines selon les expériences (étudiants en dortoir, participants à un atelier), puis ont demandé à chacun d'estimer à quel point il pensait avoir été apprécié par l'autre, et à quel point il avait réellement apprécié l'autre. Résultat constant sur plusieurs expériences : les participants sous-estiment systématiquement à quel point ils ont été appréciés. L'écart entre "ce que je pense avoir donné comme impression" et "l'impression réellement laissée" a été appelé le liking gap. Cet écart est plus fort juste après une interaction avec un inconnu, et met du temps à se refermer.

Pour la carte "L'écart de sympathie" : c'est l'argument central pour désamorcer la peur d'aborder quelqu'un. Statistiquement, ton anxiété sur "ce que l'autre a pensé de moi" est mal calibrée, dans le sens le plus rassurant.$$, $$Researchers had strangers talk in pairs, for anywhere from a few minutes to several weeks depending on the experiment (dorm students, workshop participants), then asked each person to estimate how much they thought the other person liked them, and how much they actually liked the other person. Consistent result across several experiments: participants systematically underestimate how much they were liked. The gap between "the impression I think I gave" and "the impression actually left" was named the liking gap. This gap is strongest right after an interaction with a stranger, and takes time to close.

For the "The liking gap" card: this is the central argument for defusing the fear of approaching someone. Statistically, your anxiety about "what the other person thought of me" is miscalibrated, in the most reassuring direction.$$, 'https://journals.sagepub.com/doi/10.1177/0956797618783714', true),

('a0000000-0000-0000-0000-000000000002', $$Van Edwards, Captivate (2017)$$, $$Van Edwards, Captivate (2017)$$, $$Captivate: The Science of Succeeding with People$$, $$Captivate: The Science of Succeeding with People$$, $$Van Edwards, V.$$, $$Van Edwards, V.$$, 2017, $$Portfolio/Penguin$$, $$Portfolio/Penguin$$, $$Vanessa Van Edwards dirige Science of People, un laboratoire de recherche comportementale appliquée ; son livre s'appuie sur des dizaines d'études existantes en psychologie sociale qu'elle traduit en techniques concrètes, mais le contenu lui-même (méthode FORD, "conversation sparks", techniques de relance) est une synthèse pédagogique et non une étude publiée avec sa propre méthodologie.

La méthode FORD (Famille, Occupation, loisirs/Récréation, Rêves) désigne les 4 catégories de sujets qui reviennent le plus naturellement dans une conversation entre deux personnes qui ne se connaissent pas, parce que ce sont des sujets sur lesquels la plupart des gens aiment parler d'eux-mêmes sans se sentir exposés. Le commentaire de contexte ("conversation spark") est une technique d'ouverture qui consiste à commenter l'environnement immédiat partagé plutôt que d'inventer un sujet à partir de rien. Cela réduit la pression puisque le sujet est déjà "là", sous les yeux des deux personnes. La relance par callback applique le même principe à la reprise d'une conversation après un blanc : revenir sur un élément déjà mentionné plutôt que d'ouvrir un nouveau sujet à froid.$$, $$Vanessa Van Edwards runs Science of People, an applied behavioral research lab; her book draws on dozens of existing studies in social psychology that she translates into concrete techniques, but the content itself (the FORD method, "conversation sparks," follow-up techniques) is a pedagogical synthesis rather than a published study with its own methodology.

The FORD method (Family, Occupation, Recreation, Dreams) names the 4 topic categories that come up most naturally in a conversation between two people who don't know each other, because they're subjects most people enjoy talking about themselves on without feeling exposed. The context comment ("conversation spark") is an opening technique that involves commenting on the shared immediate environment rather than inventing a topic from scratch. This lowers the pressure since the topic is already "there," in front of both people. The callback follow-up applies the same principle to picking a conversation back up after a blank: returning to something already mentioned rather than opening a new topic cold.$$, 'https://www.scienceofpeople.com/captivate/', false),

('a0000000-0000-0000-0000-000000000003', $$Huang et al., 2017$$, $$Huang et al., 2017$$, $$It Doesn't Hurt to Ask: Question-Asking Increases Liking$$, $$It Doesn't Hurt to Ask: Question-Asking Increases Liking$$, $$Huang, K., Yeomans, M., Brooks, A. W., Minson, J., & Gino, F.$$, $$Huang, K., Yeomans, M., Brooks, A. W., Minson, J., & Gino, F.$$, 2017, $$Journal of Personality and Social Psychology$$, $$Journal of Personality and Social Psychology$$, $$Cette recherche combine l'analyse de plus de 100 conversations en speed-dating et plusieurs expériences en laboratoire pour mesurer l'effet du nombre de questions posées, en particulier les questions de suivi (follow-up questions), sur la sympathie perçue par l'interlocuteur. Les personnes qui posent davantage de questions de suivi, c'est-à-dire des questions qui rebondissent directement sur ce que l'autre vient de dire, sont jugées significativement plus sympathiques et plus intéressantes par leurs interlocuteurs, indépendamment du contenu de ce qu'elles disent elles-mêmes.

La distinction entre question ouverte et question fermée en découle directement : une question ouverte donne davantage matière à l'autre pour développer, ce qui crée plus d'opportunités de questions de suivi et donc plus de sympathie perçue. Pour l'entrée dans un groupe (cours 11), le même principe s'applique : une question liée au sujet en cours a plus de chances d'être bien reçue qu'une remarque qui n'engage personne à répondre.$$, $$This research combines the analysis of more than 100 speed-dating conversations with several lab experiments to measure the effect of the number of questions asked, especially follow-up questions, on how likeable the asker is perceived to be. People who ask more follow-up questions, meaning questions that build directly on what the other person just said, are judged significantly more likeable and more interesting by their conversation partners, regardless of the content of what they themselves say.

The distinction between an open and a closed question follows directly from this: an open question gives the other person more to build on, which creates more opportunities for follow-up questions and therefore more perceived likeability. For joining a group (course 11), the same principle applies: a question tied to the current topic is more likely to land well than a remark that doesn't invite anyone to respond.$$, 'https://www.hbs.edu/ris/Publication%20Files/17-125_e5dbd393-51e1-46b5-9e18-1b6b9d2a2d43.pdf', true),

('a0000000-0000-0000-0000-000000000004', $$Headlee, TED (2015)$$, $$Headlee, TED (2015)$$, $$10 Ways to Have a Better Conversation$$, $$10 Ways to Have a Better Conversation$$, $$Headlee, C.$$, $$Headlee, C.$$, 2015, $$TED$$, $$TED$$, $$Celeste Headlee est journaliste radio et animatrice d'interviews depuis plus de 20 ans. Sa conférence TED, vue plus de 25 millions de fois, distille 10 règles tirées de sa pratique professionnelle de l'interview pour améliorer n'importe quelle conversation, parmi lesquelles : ne pas préparer sa prochaine phrase pendant que l'autre parle, ne pas prétendre savoir quand on ne sait pas, et être bref.

La règle citée dans la carte ("pose la question, puis tais-toi vraiment") vient de son observation professionnelle que les meilleurs intervieweurs laissent des silences après leurs questions au lieu de les combler, ce qui pousse naturellement l'interlocuteur à développer davantage sa réponse.$$, $$Celeste Headlee has been a radio journalist and interviewer for more than 20 years. Her TED talk, viewed more than 25 million times, distills 10 rules drawn from her professional interviewing practice for improving any conversation, including: don't prepare your next line while the other person is talking, don't pretend to know when you don't, and be brief.

The rule cited in the card ("ask, then actually stay quiet") comes from her professional observation that the best interviewers leave silences after their questions instead of filling them, which naturally pushes the other person to say more.$$, 'https://www.ted.com/talks/celeste_headlee_10_ways_to_have_a_better_conversation', false),

('a0000000-0000-0000-0000-000000000005', $$Koudenburg et al., 2011$$, $$Koudenburg et al., 2011$$, $$Disrupting the Flow: How Brief Silences in Group Conversations Affect Social Needs$$, $$Disrupting the Flow: How Brief Silences in Group Conversations Affect Social Needs$$, $$Koudenburg, N., Postmes, T., & Gordijn, E. H.$$, $$Koudenburg, N., Postmes, T., & Gordijn, E. H.$$, 2011, $$Journal of Experimental Social Psychology$$, $$Journal of Experimental Social Psychology$$, $$Les chercheurs (Université de Groningue, Pays-Bas) ont fait discuter des groupes de participants en insérant délibérément des silences très courts et minutés (de l'ordre de quelques secondes) au milieu de conversations par ailleurs fluides, puis ont mesuré l'effet sur le sentiment d'appartenance et de validation sociale des participants. Résultat : même un silence très bref suffit à activer un sentiment de menace sur le besoin d'appartenance. Les participants exposés à un silence se sentent moins acceptés par le groupe, alors même que rien de négatif n'a été dit.

Le seuil de quelques secondes (autour de 4 secondes dans les mesures reprises par la littérature de vulgarisation scientifique sur ce travail) correspond au moment où ce sentiment de menace commence à s'activer dans une conversation entre personnes qui ne se connaissent pas encore bien. D'où l'idée de la carte : au-dessous de ce seuil, le silence n'a souvent même pas eu le temps d'être perçu comme gênant par l'autre.$$, $$The researchers (University of Groningen, Netherlands) had groups of participants talk while deliberately inserting very short, precisely timed silences (on the order of a few seconds) into otherwise flowing conversations, then measured the effect on participants' sense of belonging and social validation. Result: even a very brief silence is enough to activate a sense of threat to the need to belong. Participants exposed to a silence feel less accepted by the group, even though nothing negative was said.

The threshold of a few seconds (around 4 seconds in the figures picked up by popular-science coverage of this work) corresponds to the moment this sense of threat starts to activate in a conversation between people who don't yet know each other well. Hence the idea behind the card: below that threshold, the silence often hasn't even had time to be perceived as awkward by the other person.$$, 'https://www.rug.nl/staff/n.koudenburg/koudenburgetal.2011.pdf', true),

('a0000000-0000-0000-0000-000000000006', $$Koudenburg et al., 2014$$, $$Koudenburg et al., 2014$$, $$"More Than Words": Social Validation in Close Relationships$$, $$"More Than Words": Social Validation in Close Relationships$$, $$Koudenburg, N., Postmes, T., & Gordijn, E. H.$$, $$Koudenburg, N., Postmes, T., & Gordijn, E. H.$$, 2014, $$Personality and Social Psychology Bulletin$$, $$Personality and Social Psychology Bulletin$$, $$Ce travail prolonge la recherche de 2011 en comparant l'effet des silences et disruptions de flux conversationnel entre inconnus versus entre personnes ayant une relation établie. Chez des proches, les chercheurs montrent que le silence n'active pas la même alarme sociale : les partenaires s'appuient sur leur relation existante ("on n'a pas besoin de mots pour se comprendre") pour interpréter le silence comme un signe de confort plutôt que de rejet.

Pour la carte : ça recadre la gêne du silence comme un phénomène propre au stade de la relation (inconnu ou connaissance récente), pas comme un déficit de compétence sociale permanent : l'inconfort du silence diminue naturellement à mesure que la relation se construit.$$, $$This work extends the 2011 research by comparing the effect of silences and conversational-flow disruptions between strangers versus between people with an established relationship. Among close partners, the researchers show that silence doesn't activate the same social alarm: partners rely on their existing relationship ("we don't need words to understand each other") to interpret silence as a sign of comfort rather than rejection.

For the card: this reframes discomfort with silence as tied to the stage of the relationship (stranger or recent acquaintance), not as a permanent social-skill deficit: discomfort with silence naturally decreases as the relationship builds.$$, 'https://journals.sagepub.com/doi/10.1177/0146167214549945', true),

('a0000000-0000-0000-0000-000000000007', $$Mastroianni et al., 2021$$, $$Mastroianni et al., 2021$$, $$Do Conversations End When People Want Them To?$$, $$Do Conversations End When People Want Them To?$$, $$Mastroianni, A. M., Gilbert, D. T., Cooney, G., & Wilson, T. D.$$, $$Mastroianni, A. M., Gilbert, D. T., Cooney, G., & Wilson, T. D.$$, 2021, $$Proceedings of the National Academy of Sciences (PNAS)$$, $$Proceedings of the National Academy of Sciences (PNAS)$$, $$Les chercheurs ont interrogé les deux membres de centaines de paires de conversants juste après leur échange, en leur demandant séparément et confidentiellement à quel moment ils auraient voulu que la conversation se termine. Résultat : les deux personnes se sont mises d'accord sur le bon moment pour arrêter dans moins de 2% des cas. Environ 48% des conversations ont duré plus longtemps que ce qu'au moins une des deux personnes souhaitait, et 34% se sont arrêtées trop tôt aux yeux d'au moins l'une des deux. En moyenne, les participants auraient souhaité que leur conversation dure environ 2 minutes de plus ou de moins que sa durée réelle. Les chercheurs expliquent ce résultat par un "problème de coordination" : personne ne révèle son envie réelle de partir, donc personne ne peut savoir quand l'autre est prêt à arrêter.

Pour les 3 cartes qui s'appuient dessus : ça déplace la responsabilité perçue ("est-ce que JE fais mal les choses en voulant partir ?") vers un phénomène statistiquement universel qui touche presque toutes les conversations, dans les deux sens.$$, $$The researchers surveyed both members of hundreds of conversation pairs right after their exchange, asking each of them separately and confidentially at what point they would have wanted the conversation to end. Result: the two people agreed on the right moment to stop in fewer than 2% of cases. About 48% of conversations lasted longer than at least one of the two people wanted, and 34% ended too soon in the eyes of at least one of them. On average, participants would have wanted their conversation to last about 2 minutes more or less than its actual length. The researchers explain this result as a "coordination problem": no one reveals their real wish to leave, so no one can know when the other person is ready to stop.

For the 3 cards built on this: it shifts the perceived responsibility ("am I doing something wrong by wanting to leave?") toward a statistically universal phenomenon that affects almost every conversation, in both directions.$$, 'https://www.pnas.org/doi/10.1073/pnas.2011809118', true),

('a0000000-0000-0000-0000-000000000008', $$Sortie en 3 temps (pratique)$$, $$The 3-step exit (practical)$$, $$La sortie en 3 temps$$, $$The 3-step exit$$, $$Technique de coaching en communication$$, $$Communication coaching technique$$, null, null, null, $$Cette structure en 3 temps (observation/prétexte de départ → raison brève sans sur-justification → formule de clôture chaleureuse) est une technique de communication couramment enseignée en coaching, construite sur un principe de bon sens plutôt que sur une étude isolée : plus une excuse est longue et détaillée, plus elle donne l'impression de devoir se justifier, et plus elle laisse de prise à l'autre pour prolonger l'échange ou négocier. Elle est cohérente avec la logique de la recherche de Mastroianni et al. : puisque l'autre ne sait de toute façon pas précisément quand tu veux partir, une sortie courte et nette est suffisante, inutile de la sur-justifier.$$, $$This 3-step structure (observation/departure cue → brief reason without over-justifying → warm closing line) is a communication technique commonly taught in coaching, built on common sense rather than a single isolated study: the longer and more detailed an excuse is, the more it looks like you feel you need to justify yourself, and the more room it gives the other person to prolong the exchange or negotiate. It's consistent with the logic of Mastroianni et al.'s research: since the other person doesn't know precisely when you want to leave anyway, a short, clean exit is enough, no need to over-justify it.$$, 'https://www.pnas.org/doi/10.1073/pnas.2011809118', false),

('a0000000-0000-0000-0000-000000000009', $$Eysenck, 1967$$, $$Eysenck, 1967$$, $$The Biological Basis of Personality$$, $$The Biological Basis of Personality$$, $$Eysenck, H. J.$$, $$Eysenck, H. J.$$, 1967, $$Charles C. Thomas$$, $$Charles C. Thomas$$, $$Hans Eysenck a proposé que la différence entre introversion et extraversion repose sur une différence biologique de niveau d'éveil cortical (cortical arousal), régulé par une structure du tronc cérébral appelée la formation réticulée activatrice ascendante. Selon cette théorie, les introvertis ont un niveau d'éveil cortical de base déjà plus élevé au repos que les extravertis. Leur système nerveux atteint donc plus vite son seuil optimal de stimulation, après quoi toute stimulation supplémentaire (sociale, sensorielle) devient inconfortable plutôt qu'agréable. Les extravertis, à l'inverse, partent d'un niveau d'éveil plus bas et recherchent activement la stimulation pour atteindre leur propre seuil optimal. Cette théorie reste, plus de 50 ans après sa publication, l'explication biologique de référence de la fatigue sociale différenciée entre profils de personnalité, reprise et affinée par des travaux ultérieurs en neurosciences de la personnalité.

Pour les cartes : ça explique pourquoi la fatigue post-événement n'est pas "dans la tête" mais correspond à un mécanisme physiologique mesurable, et pourquoi les activités à faible stimulation sensorielle (plutôt que les activités qui continuent de solliciter l'attention) permettent au système nerveux de redescendre sous son seuil.$$, $$Hans Eysenck proposed that the difference between introversion and extraversion rests on a biological difference in baseline cortical arousal, regulated by a brainstem structure called the ascending reticular activating system. According to this theory, introverts have a higher baseline cortical arousal level at rest than extraverts. Their nervous system therefore reaches its optimal stimulation threshold faster, after which any additional stimulation (social, sensory) becomes uncomfortable rather than pleasant. Extraverts, by contrast, start from a lower arousal level and actively seek out stimulation to reach their own optimal threshold. More than 50 years after its publication, this theory remains the reference biological explanation for differences in social fatigue between personality profiles, picked up and refined by later work in the neuroscience of personality.

For the cards: this explains why post-event fatigue isn't "in your head" but corresponds to a measurable physiological mechanism, and why low-sensory-stimulation activities (rather than activities that keep demanding attention) let the nervous system settle back below its threshold.$$, 'https://hanseysenck.com/wp-content/uploads/2019/12/1991_eysenck_-_dimensions_of_personality_the_biosocial_approach_to_personality.pdf', true),

('a0000000-0000-0000-0000-000000000010', $$Little, Free Trait Theory$$, $$Little, Free Trait Theory$$, $$Acting Out of Character in the Immortal Profession: Toward a Free Trait Agreement$$, $$Acting Out of Character in the Immortal Profession: Toward a Free Trait Agreement$$, $$Little, B. R.$$, $$Little, B. R.$$, null, null, null, $$Brian Little a développé la "Free Trait Theory" : l'idée que chacun peut, temporairement, agir "hors de son tempérament naturel" (par exemple un introverti qui se comporte de façon extravertie lors d'un événement professionnel) pour poursuivre un projet personnel important. Mais ce comportement "hors caractère" a un coût cumulatif, et nécessite en retour un temps de récupération dans un environnement qui correspond au tempérament de base de la personne. Little appelle ça une "niche restauratrice" (pour un introverti biogénique : solitude, stimulation réduite). Il propose également le concept de "Free Trait Agreement" : négocier explicitement avec son entourage (partenaire, collègues) le droit à ce temps de récupération en échange d'accepter d'agir hors caractère quand c'est nécessaire.

Pour les cartes : ça donne un cadre concret pour comprendre pourquoi la récupération après un événement social n'est pas un luxe mais une nécessité physiologique, et pourquoi la négocier à l'avance (plutôt que de s'en excuser après coup) est une stratégie reconnue plutôt qu'un caprice.$$, $$Brian Little developed "Free Trait Theory": the idea that anyone can, temporarily, act "out of character" (for example, an introvert behaving in an extraverted way at a work event) in pursuit of an important personal project. But this "out of character" behavior has a cumulative cost, and requires, in return, recovery time in an environment matching the person's baseline temperament. Little calls this a "restorative niche" (for a biogenic introvert: solitude, reduced stimulation). He also proposes the concept of a "Free Trait Agreement": explicitly negotiating with the people around you (partner, coworkers) for the right to this recovery time in exchange for agreeing to act out of character when needed.

For the cards: this gives a concrete framework for understanding why recovery after a social event isn't a luxury but a physiological necessity, and why negotiating it in advance (rather than apologizing for it afterward) is a recognized strategy rather than a whim.$$, 'https://www.brianrlittle.com/articles/acting-out-of-character-in-the-immortal-profession-toward-a-free-trait-agreement/', true),

('a0000000-0000-0000-0000-000000000011', $$Clark & Wells, 1995$$, $$Clark & Wells, 1995$$, $$A Cognitive Model of Social Phobia$$, $$A Cognitive Model of Social Phobia$$, $$Clark, D. M., & Wells, A.$$, $$Clark, D. M., & Wells, A.$$, 1995, $$In Social Phobia: Diagnosis, Assessment, and Treatment$$, $$In Social Phobia: Diagnosis, Assessment, and Treatment$$, $$Ce modèle, l'un des plus influents en thérapie cognitivo-comportementale (TCC), décrit les mécanismes qui entretiennent l'anxiété sociale : des pensées automatiques négatives sur soi ("je vais être gênant"), une attention excessive tournée vers soi-même plutôt que vers la situation réelle, des "comportements de sécurité" censés protéger mais qui en réalité renforcent l'anxiété (répéter mentalement ce qu'on va dire, éviter le regard, sur-préparer), et un traitement anticipatoire et rétrospectif de l'événement ("pre-event processing" avant, et "post-event processing" après). Le modèle a donné naissance à un protocole de thérapie dont l'efficacité a été validée par de nombreux essais cliniques ultérieurs.

Pour les cartes du cours 5 : chacun des mécanismes du modèle correspond directement à une carte : la rumination anticipatoire (carte 1), les pensées automatiques (carte 2), les comportements de sécurité (carte 3), et la comparaison prédiction/réalité comme moyen de casser le cycle (carte 4). Pour le niveau 2 : la distinction entre les faits objectifs et l'interprétation qu'on en fait est au cœur de la restructuration cognitive proposée par ce modèle.$$, $$This model, one of the most influential in cognitive behavioral therapy (CBT), describes the mechanisms that sustain social anxiety: negative automatic thoughts about oneself ("I'm going to be awkward"), excessive attention turned toward oneself rather than the actual situation, "safety behaviors" meant to protect but that actually reinforce anxiety (mentally rehearsing what you'll say, avoiding eye contact, over-preparing), and anticipatory and retrospective processing of the event ("pre-event processing" before, and "post-event processing" after). The model gave rise to a therapy protocol whose effectiveness has been validated by numerous later clinical trials.

For course 5's cards: each mechanism in the model maps directly to a card: anticipatory rumination (card 1), automatic thoughts (card 2), safety behaviors (card 3), and comparing prediction to reality as a way to break the cycle (card 4). For level 2: the distinction between objective facts and the interpretation you draw from them is at the heart of the cognitive restructuring this model proposes.$$, 'https://www.psychologytools.com/resource/cognitive-behavioral-model-of-social-phobia-clark-wells-1995', true),

('a0000000-0000-0000-0000-000000000012', $$Abrahams, 2023$$, $$Abrahams, 2023$$, $$Think Faster, Talk Smarter: How to Speak Successfully When You're Put on the Spot$$, $$Think Faster, Talk Smarter: How to Speak Successfully When You're Put on the Spot$$, $$Abrahams, M.$$, $$Abrahams, M.$$, 2023, $$Simon & Schuster$$, $$Simon & Schuster$$, $$Matt Abrahams enseigne la communication stratégique et la prise de parole spontanée à la Stanford Graduate School of Business, et anime le podcast Think Fast, Talk Smart. Son livre s'appuie sur des années d'enseignement et sur son expérience en théâtre d'improvisation, mais présente un ensemble de techniques pratiques plutôt qu'une étude à méthodologie contrôlée.

Deux principes en particulier sont ses recommandations centrales pour gérer les moments où l'on doit parler sans préparation : viser une réponse "suffisamment bonne" plutôt que parfaite pour libérer la charge mentale, et préparer des phrases-pont réutilisables ("c'est une bonne question, laisse-moi y réfléchir").$$, $$Matt Abrahams teaches strategic communication and spontaneous speaking at the Stanford Graduate School of Business, and hosts the podcast Think Fast, Talk Smart. His book draws on years of teaching and his experience in improv theater, but presents a set of practical techniques rather than a controlled-methodology study.

Two principles in particular are his central recommendations for handling moments when you have to speak without preparation: aiming for a "good enough" answer rather than a perfect one to free up mental bandwidth, and preparing reusable bridge phrases ("that's a good question, let me think about it").$$, 'https://www.simonandschuster.com/books/Think-Faster-Talk-Smarter/Matt-Abrahams/9781668010303', false),

('a0000000-0000-0000-0000-000000000013', $$Felsman et al., 2020$$, $$Felsman et al., 2020$$, $$Improv Experience Promotes Divergent Thinking, Uncertainty Tolerance, and Affective Well-Being$$, $$Improv Experience Promotes Divergent Thinking, Uncertainty Tolerance, and Affective Well-Being$$, $$Felsman, P., Gunawardena, S., & Seifert, C. M.$$, $$Felsman, P., Gunawardena, S., & Seifert, C. M.$$, 2020, $$Thinking Skills and Creativity$$, $$Thinking Skills and Creativity$$, $$Deux expériences contrôlées, avec les échantillons les plus larges jamais utilisés pour une étude expérimentale sur l'improvisation théâtrale : dans la première, un groupe suivait un atelier d'improvisation pendant qu'un groupe témoin participait à une interaction sociale structurée mais scriptée (parler d'un ami, d'un film, faire des actions physiques prévues à l'avance). Le groupe improvisation a montré une amélioration plus marquée de la pensée divergente (la capacité à générer plusieurs idées face à une situation ouverte), et les deux groupes ont progressé sur le bien-être ressenti et la tolérance à l'incertitude. Dans la seconde expérience, où le groupe témoin suivait des tâches sociales scriptées (sans place à l'improvisation), seul le groupe improvisation a montré une amélioration significative des émotions positives et de la tolérance à l'incertitude.

Pour les cartes : ça montre que la capacité à "gérer l'imprévu" dans une conversation (comme un blanc mental) n'est pas un trait fixe mais une compétence mesurablement entraînable, et que le principe central de l'improvisation (accepter ce qui arrive plutôt que lutter contre) est ce qui produit l'effet.$$, $$Two controlled experiments, with the largest samples ever used for an experimental study on improv theater: in the first, one group took an improv workshop while a control group took part in a structured but scripted social interaction (talking about a friend, a movie, doing physical actions planned in advance). The improv group showed a more marked improvement in divergent thinking (the ability to generate multiple ideas in response to an open-ended situation), and both groups improved on felt well-being and tolerance for uncertainty. In the second experiment, where the control group followed scripted social tasks (with no room for improvisation), only the improv group showed a significant improvement in positive emotions and tolerance for uncertainty.

For the cards: this shows that the ability to "handle the unexpected" in a conversation (like a mental blank) isn't a fixed trait but a measurably trainable skill, and that improv's core principle (accepting what happens rather than fighting it) is what produces the effect.$$, 'https://www.sciencedirect.com/science/article/abs/pii/S1871187119302470', true),

('a0000000-0000-0000-0000-000000000014', $$Gottman & Levenson$$, $$Gottman & Levenson$$, $$Recherche longitudinale sur le "harsh startup" et les "repair attempts"$$, $$Longitudinal research on the "harsh startup" and "repair attempts"$$, $$Gottman, J. M., & Levenson, R. W.$$, $$Gottman, J. M., & Levenson, R. W.$$, null, null, null, $$John Gottman et Robert Levenson ont filmé et codé des milliers de conversations et de disputes de couples et de familles sur plusieurs décennies, en suivant certains participants pendant plus de 20 ans pour corréler leurs schémas de communication avec l'issue de leur relation. Deux résultats majeurs de ce corpus sont mobilisés ici : le "harsh startup" (démarrage brutal), la façon dont une discussion commence dans ses toutes premières minutes et qui prédit avec une très forte précision comment elle va se terminer, un démarrage critique ou accusateur menant presque systématiquement à une escalade ; et les "repair attempts" (tentatives de réparation), tout geste, phrase ou trait d'humour qui vise à désamorcer une tension montante avant qu'elle ne dégénère. Ce qui distingue le mieux les relations qui durent, selon Gottman, n'est pas l'absence de conflit mais la capacité à réparer efficacement en cours de dispute, et le fait que ces tentatives soient reçues par l'autre.

Pour les cartes : ça justifie l'idée de désamorcer dès les premières secondes d'un sujet sensible plutôt que d'attendre que ça s'envenime, et de valoriser une tentative de réparation (humour, redirection) plutôt que d'entrer dans le fond du désaccord.$$, $$John Gottman and Robert Levenson filmed and coded thousands of conversations and arguments among couples and families over several decades, following some participants for more than 20 years to correlate their communication patterns with how their relationship turned out. Two major findings from this body of work are drawn on here: the "harsh startup," the way a discussion begins in its very first minutes, which predicts with very high accuracy how it will end, a critical or accusatory start almost always leading to escalation; and "repair attempts," any gesture, line, or touch of humor aimed at defusing rising tension before it turns into a full-blown fight. What best distinguishes relationships that last, according to Gottman, isn't the absence of conflict but the ability to repair effectively mid-argument, and whether those attempts are received by the other person.

For the cards: this supports the idea of defusing a sensitive topic from the first seconds rather than waiting for it to fester, and valuing a repair attempt (humor, redirection) over engaging with the substance of the disagreement.$$, 'https://www.gottman.com/blog/r-is-for-repair/', true),

('a0000000-0000-0000-0000-000000000015', $$Redirection neutre (pratique)$$, $$Neutral redirection (practical)$$, $$Technique de redirection neutre$$, $$Neutral redirection technique$$, $$Technique de gestion de conflit$$, $$Conflict management technique$$, null, null, null, $$Rediriger une conversation vers un sujet neutre sans confronter frontalement le sujet sensible est une technique de désescalade communément enseignée en gestion de conflit, cohérente avec la logique du "harsh startup" de Gottman & Levenson : elle évite de transformer un désaccord ponctuel en confrontation ouverte, sans pour autant nécessiter de débat sur le fond.$$, $$Redirecting a conversation to a neutral topic without directly confronting the sensitive subject is a de-escalation technique commonly taught in conflict management, consistent with Gottman & Levenson's "harsh startup" logic: it avoids turning a one-off disagreement into open confrontation, without requiring a debate on the substance.$$, 'https://www.gottman.com/blog/r-is-for-repair/', false),

('a0000000-0000-0000-0000-000000000016', $$Hall, 2019$$, $$Hall, 2019$$, $$How Many Hours Does It Take to Make a Friend?$$, $$How Many Hours Does It Take to Make a Friend?$$, $$Hall, J. A.$$, $$Hall, J. A.$$, 2019, $$Journal of Social and Personal Relationships$$, $$Journal of Social and Personal Relationships$$, $$Jeffrey Hall (Université du Kansas) a mené deux études rétrospectives auprès de plusieurs centaines d'adultes ayant récemment déménagé ou noué une nouvelle relation, en leur demandant d'estimer le temps total passé avec une personne donnée à différents stades de leur amitié. En croisant ces données, il établit des seuils approximatifs : environ 40 à 60 heures cumulées pour passer du statut de simple connaissance à ami "occasionnel", 80 à 100 heures pour devenir ami, et plus de 200 heures pour devenir ami proche. Un résultat notable : le temps passé dans un cadre professionnel structuré (travailler ensemble) contribue beaucoup moins à ces heures que le temps de loisir ou les interactions informelles et spontanées.

Pour les cartes : ça recadre l'amitié adulte comme une question de temps cumulé et de récurrence plutôt que d'alchimie instantanée. Ça justifie de privilégier des activités récurrentes (où les heures s'accumulent naturellement) à des rencontres isolées, même nombreuses.$$, $$Jeffrey Hall (University of Kansas) ran two retrospective studies with several hundred adults who had recently moved or formed a new relationship, asking them to estimate the total time spent with a given person at different stages of their friendship. Cross-referencing this data, he establishes approximate thresholds: about 40 to 60 cumulative hours to move from mere acquaintance to "casual" friend, 80 to 100 hours to become a friend, and more than 200 hours to become a close friend. One notable finding: time spent in a structured professional setting (working together) contributes much less to these hours than leisure time or informal, spontaneous interactions.

For the cards: this reframes adult friendship as a matter of accumulated time and recurrence rather than instant chemistry. It supports favoring recurring activities (where hours build up naturally) over isolated meetings, even many of them.$$, 'https://journals.sagepub.com/doi/full/10.1177/0265407518761225', true),

('a0000000-0000-0000-0000-000000000017', $$Methot et al., 2021$$, $$Methot et al., 2021$$, $$Office Chitchat as a Social Ritual: The Uplifting Yet Distracting Effects of Daily Small Talk at Work$$, $$Office Chitchat as a Social Ritual: The Uplifting Yet Distracting Effects of Daily Small Talk at Work$$, $$Methot, J. R., Rosado-Solomon, E. H., Downes, P. E., & Gabriel, A. S.$$, $$Methot, J. R., Rosado-Solomon, E. H., Downes, P. E., & Gabriel, A. S.$$, 2021, $$Academy of Management Journal$$, $$Academy of Management Journal$$, $$Les chercheurs ont suivi 151 employés à temps plein pendant plusieurs semaines, en leur demandant de rapporter chaque jour la quantité de small talk échangée et leur état émotionnel/niveau d'engagement au travail. Résultat en deux volets : le small talk quotidien augmente les émotions positives et le sentiment de bien-être en fin de journée, et rend les employés plus enclins à des comportements d'entraide envers leurs collègues ; mais il a aussi un effet de distraction mesurable, réduisant temporairement la capacité de concentration sur les tâches. Les chercheurs résument cet effet double par l'expression "uplifting yet distracting" (stimulant mais distrayant), avec un bilan globalement positif pour le bien-être.

Pour les cartes : ça légitime le small talk comme un vrai contributeur au bien-être au travail (pas juste une politesse creuse), tout en justifiant de le cadrer dans le temps pour limiter son coût cognitif plutôt que de l'éviter ou de le culpabiliser.$$, $$The researchers followed 151 full-time employees over several weeks, asking them to report each day how much small talk they'd exchanged and their emotional state/level of engagement at work. Two-part result: daily small talk increases positive emotions and end-of-day well-being, and makes employees more inclined toward helping behaviors with coworkers; but it also has a measurable distracting effect, temporarily reducing focus on tasks. The researchers sum up this double effect with the phrase "uplifting yet distracting," with an overall positive balance for well-being.

For the cards: this legitimizes small talk as a genuine contributor to well-being at work (not just hollow politeness), while supporting keeping it time-boxed to limit its cognitive cost rather than avoiding it or feeling guilty about it.$$, 'https://journals.aom.org/doi/abs/10.5465/amj.2018.1474', true),

('a0000000-0000-0000-0000-000000000018', $$Méta-analyse assertivité$$, $$Assertiveness meta-analysis$$, $$A Meta-Analysis of Randomised Controlled Trials on the Efficacy of Assertiveness Training for Social Anxiety$$, $$A Meta-Analysis of Randomised Controlled Trials on the Efficacy of Assertiveness Training for Social Anxiety$$, $$Méta-analyse$$, $$Meta-analysis$$, null, $$International Journal of Applied Positive Psychology$$, $$International Journal of Applied Positive Psychology$$, $$Cette méta-analyse rassemble les résultats de 12 essais contrôlés randomisés portant au total sur plus de 500 participants, comparant des personnes ayant suivi un entraînement structuré à l'affirmation de soi (assertiveness training) à des groupes témoins. L'analyse combinée obtient une taille d'effet moyenne (g = 0,62), ce qui correspond à un effet mesurable et cliniquement significatif sur le comportement assertif et sur la réduction de l'anxiété sociale associée aux situations nécessitant de poser une limite.

Pour les cartes : ça établit que poser une limite sans culpabiliser n'est pas un trait de personnalité qu'on a ou qu'on n'a pas, mais une compétence pour laquelle l'entraînement a un effet démontré, y compris sur la gêne et la culpabilité initiale ressentie, qui diminue avec la pratique répétée.$$, $$This meta-analysis pools the results of 12 randomized controlled trials covering more than 500 participants in total, comparing people who underwent structured assertiveness training to control groups. The pooled analysis finds an average effect size (g = 0.62), corresponding to a measurable, clinically significant effect on assertive behavior and on reducing the social anxiety associated with situations that require setting a boundary.

For the cards: this establishes that setting a boundary without guilt isn't a personality trait you either have or don't, but a skill for which training has a demonstrated effect, including on the initial discomfort and guilt felt, which decreases with repeated practice.$$, 'https://link.springer.com/article/10.1007/s41042-026-00297-7', true),

('a0000000-0000-0000-0000-000000000019', $$Formule DESC (pratique)$$, $$The DESC formula (practical)$$, $$La formule DESC$$, $$The DESC formula$$, $$Outil de communication assertive$$, $$Assertive communication tool$$, null, null, null, $$DESC (Décrire les faits, Exprimer son ressenti, Spécifier ce qu'on propose, indiquer les Conséquences positives) est un acronyme pédagogique utilisé depuis plusieurs décennies dans les formations à la communication assertive et à la gestion de conflit, dérivé des principes généraux de l'entraînement à l'assertivité dont l'efficacité globale est établie par la méta-analyse citée par ailleurs (mais DESC en tant que structure précise n'a pas été isolément testée par un essai contrôlé dédié).$$, $$DESC (Describe the facts, Express your feelings, Specify what you're proposing, state the positive Consequences) is a teaching acronym used for several decades in assertive-communication and conflict-management training, derived from the general principles of assertiveness training whose overall effectiveness is established by the meta-analysis cited elsewhere (though DESC as a precise structure hasn't itself been tested in isolation by a dedicated controlled trial).$$, 'https://link.springer.com/article/10.1007/s41042-026-00297-7', false),

('a0000000-0000-0000-0000-000000000020', $$Dire non sans se justifier (pratique)$$, $$Saying no without justifying yourself (practical)$$, $$Dire non sans se justifier$$, $$Saying no without justifying yourself$$, $$Principe de communication assertive$$, $$Assertive communication principle$$, null, null, null, $$Le principe qu'une phrase courte et sans sur-justification est plus efficace qu'une explication longue est un classique de la formation à l'assertivité : plus la justification est développée, plus elle offre de prises à l'autre pour négocier ou remettre en question la limite posée. Cohérent avec l'effet global démontré par la méta-analyse sur l'entraînement à l'assertivité, sans être lui-même le sujet d'un essai contrôlé isolé.$$, $$The principle that a short sentence without over-justification is more effective than a long explanation is a classic of assertiveness training: the more elaborate the justification, the more openings it gives the other person to negotiate or challenge the boundary set. Consistent with the overall effect demonstrated by the meta-analysis on assertiveness training, without itself being the subject of an isolated controlled trial.$$, 'https://link.springer.com/article/10.1007/s41042-026-00297-7', false),

('a0000000-0000-0000-0000-000000000021', $$Kardas, Kumar & Epley, 2022$$, $$Kardas, Kumar & Epley, 2022$$, $$Overly Shallow?: Miscalibrated Expectations Create a Barrier to Deeper Conversation$$, $$Overly Shallow?: Miscalibrated Expectations Create a Barrier to Deeper Conversation$$, $$Kardas, M., Kumar, A., & Epley, N.$$, $$Kardas, M., Kumar, A., & Epley, N.$$, 2022, $$Journal of Personality and Social Psychology$$, $$Journal of Personality and Social Psychology$$, $$12 expériences menées sur plus de 1800 participants au total. Dans le protocole type, des paires d'inconnus recevaient soit des questions superficielles (la météo, un film, une mauvaise coupe de cheveux), soit des questions bien plus personnelles (ce dont ils sont le plus reconnaissants, ce qu'ils changeraient dans leur éducation, la dernière fois qu'ils ont pleuré devant quelqu'un). Avant l'échange, chaque participant prédisait à quel point la conversation serait gênante, connectante et agréable ; après l'échange, il évaluait ce qu'il avait réellement vécu. Résultat constant : les conversations profondes se sont révélées systématiquement moins gênantes et plus connectantes que prévu par les deux parties, l'écart de prédiction étant plus marqué pour les échanges profonds que pour les échanges superficiels.

Pour les cartes : ça démontre que la barrière perçue à approfondir une conversation ("ça va mettre l'autre mal à l'aise") est une erreur de calibration prévisible et mesurée, pas un risque réel. Les échanges les plus réussis dans l'étude étaient réciproques, ce qui justifie l'idée de partager à la même profondeur que ce qu'on demande.$$, $$12 experiments with more than 1,800 participants in total. In the typical protocol, pairs of strangers received either shallow questions (the weather, a movie, a bad haircut) or much more personal ones (what they're most grateful for, what they'd change about their upbringing, the last time they cried in front of someone). Before the exchange, each participant predicted how awkward, connecting, and enjoyable the conversation would be; after the exchange, they rated what they'd actually experienced. Consistent result: deep conversations turned out to be systematically less awkward and more connecting than both sides predicted, with the prediction gap being larger for deep exchanges than for shallow ones.

For the cards: this demonstrates that the perceived barrier to deepening a conversation ("it'll make the other person uncomfortable") is a predictable, measured calibration error, not a real risk. The most successful exchanges in the study were reciprocal, which supports the idea of sharing at the same depth you're asking for.$$, 'https://pubmed.ncbi.nlm.nih.gov/34591541/', true),

('a0000000-0000-0000-0000-000000000022', $$Rachman et al., 2000$$, $$Rachman et al., 2000$$, $$Post-Event Processing in Social Anxiety$$, $$Post-Event Processing in Social Anxiety$$, $$Rachman, S., Gruter-Andrew, J., & Shafran, R.$$, $$Rachman, S., Gruter-Andrew, J., & Shafran, R.$$, 2000, $$Behaviour Research and Therapy, 38(6)$$, $$Behaviour Research and Therapy, 38(6)$$, $$Cette étude psychométrique, menée par S. Rachman, J. Gruter-Andrew et R. Shafran (University of British Columbia), a développé et validé l'un des premiers outils de mesure du "post-event processing", la tendance à repasser en boucle un événement social après coup. Le score de post-event processing s'est révélé significativement corrélé (r = 0,40) au niveau d'anxiété sociale général des participants. L'étude décrit ce processus comme des souvenirs récurrents et intrusifs qui interfèrent avec la concentration sur d'autres tâches, et montre qu'il est associé à l'évitement de situations sociales similaires par la suite. Ce concept, largement influencé par le modèle de Clark & Wells publié 5 ans plus tôt, en constitue la validation empirique pour la phase "après l'événement" du modèle.

Pour les cartes : ça donne un nom et une base de mesure clinique à un phénomène que beaucoup vivent sans le nommer, et établit que la rumination n'est pas un simple "y repenser" neutre mais un processus actif qui est corrélé à l'anxiété sociale, et qui l'entretient.$$, $$This psychometric study, conducted by S. Rachman, J. Gruter-Andrew, and R. Shafran (University of British Columbia), developed and validated one of the first tools for measuring "post-event processing," the tendency to replay a social event on a loop afterward. The post-event processing score turned out to be significantly correlated (r = 0.40) with participants' general level of social anxiety. The study describes this process as recurring, intrusive memories that interfere with concentration on other tasks, and shows that it's associated with subsequently avoiding similar social situations. This concept, heavily influenced by the Clark & Wells model published 5 years earlier, serves as its empirical validation for the model's "after the event" phase.

For the cards: this gives a name and a clinical measurement basis to a phenomenon many people experience without naming it, and establishes that rumination isn't just neutrally "thinking back" but an active process that's correlated with, and sustains, social anxiety.$$, 'https://pubmed.ncbi.nlm.nih.gov/10846809/', true),

('a0000000-0000-0000-0000-000000000023', $$Fenêtre de rumination (pratique)$$, $$The rumination window (practical)$$, $$La fenêtre de rumination$$, $$The rumination window$$, $$Technique de gestion du temps de rumination (TCC)$$, $$Rumination time-management technique (CBT)$$, null, null, null, $$Limiter la rumination à une fenêtre de temps définie plutôt que de la laisser envahir la journée est un principe de contrôle du stimulus couramment utilisé en TCC pour la gestion de l'inquiétude et de la rumination de façon plus générale. Il est cohérent avec la logique du post-event processing : contenir le processus dans un cadre limité réduit son emprise sur le reste des activités quotidiennes, sans prétendre à une validation par un essai contrôlé spécifique à cette formulation exacte.$$, $$Limiting rumination to a defined time window rather than letting it take over the day is a stimulus-control principle commonly used in CBT for managing worry and rumination more generally. It's consistent with the logic of post-event processing: containing the process within a limited frame reduces its grip on the rest of daily activities, without claiming validation from a controlled trial specific to this exact formulation.$$, 'https://pubmed.ncbi.nlm.nih.gov/10846809/', false),

('a0000000-0000-0000-0000-000000000024', $$Roberts & Dunbar, 2015$$, $$Roberts & Dunbar, 2015$$, $$Managing Relationship Decay: Network, Gender, and Contextual Effects$$, $$Managing Relationship Decay: Network, Gender, and Contextual Effects$$, $$Roberts, S. G. B., & Dunbar, R. I. M.$$, $$Roberts, S. G. B., & Dunbar, R. I. M.$$, 2015, $$Human Nature, 26$$, $$Human Nature, 26$$, $$Étude longitudinale sur 18 mois ayant suivi l'évolution du réseau social actif de participants traversant une transition de vie majeure (un déménagement), en mesurant à intervalles réguliers la fréquence de contact et le niveau de proximité émotionnelle avec chaque relation citée. Résultat central : contrairement aux liens familiaux, qui résistent relativement bien à l'absence de contact, les amitiés se dégradent mesurablement sans investissement actif régulier. La proximité émotionnelle diminue en creux du manque de contact, sans qu'il y ait besoin d'un conflit. L'étude observe aussi une différence de genre dans le levier qui protège le mieux la relation : la fréquence des échanges verbaux pour les femmes, la pratique d'activités partagées pour les hommes.

Pour les cartes : ça établit factuellement que l'érosion progressive d'une amitié adulte n'est pas une fatalité relationnelle mais un phénomène lié au manque d'entretien actif. Ça justifie de le traiter comme quelque chose à planifier plutôt que de compter sur la spontanéité.$$, $$An 18-month longitudinal study that tracked the evolution of participants' active social network as they went through a major life transition (a move), measuring at regular intervals the frequency of contact and the level of emotional closeness with each relationship named. Central finding: unlike family ties, which hold up relatively well against a lack of contact, friendships measurably decay without regular active investment. Emotional closeness dips in step with the lack of contact, with no conflict needed. The study also observes a gender difference in which lever best protects the relationship: frequency of verbal exchange for women, shared activities for men.

For the cards: this factually establishes that the gradual erosion of an adult friendship isn't a relational inevitability but a phenomenon tied to a lack of active upkeep. It supports treating it as something to plan for rather than relying on spontaneity.$$, 'https://link.springer.com/article/10.1007/s12110-015-9242-7', true),

('a0000000-0000-0000-0000-000000000025', $$Kendon, 1990$$, $$Kendon, 1990$$, $$Conducting Interaction: Patterns of Behavior in Focused Encounters$$, $$Conducting Interaction: Patterns of Behavior in Focused Encounters$$, $$Kendon, A.$$, $$Kendon, A.$$, 1990, $$Cambridge University Press$$, $$Cambridge University Press$$, $$Adam Kendon, pionnier de l'étude des comportements non-verbaux et de la proxémie, a formalisé le concept de "F-formation" (facing formation) : la façon dont deux personnes ou plus se positionnent spatialement lorsqu'elles interagissent, de manière à créer un espace commun (o-space) auquel elles ont un accès égal et exclusif. Kendon décrit plusieurs configurations types (face à face, côte à côte, en L, en cercle) et montre que ces arrangements spatiaux ne sont pas aléatoires mais suivent des règles implicites que les participants respectent inconsciemment, y compris la façon dont un groupe "laisse un espace" ouvert ou au contraire ferme complètement son cercle.

Pour les cartes : ça donne une base scientifique au ressenti intuitif qu'un groupe est "ouvert" ou "fermé" à l'entrée d'une nouvelle personne. L'ouverture spatiale du cercle est un signal social réel, étudié et documenté, pas une simple impression.

Note : ce lien pointe vers une figure illustrant le concept plutôt que vers l'ouvrage original (1990, pas de version numérique librement accessible).$$, $$Adam Kendon, a pioneer in the study of nonverbal behavior and proxemics, formalized the concept of the "F-formation" (facing formation): the way two or more people position themselves spatially when interacting, so as to create a shared space (o-space) to which they have equal, exclusive access. Kendon describes several typical configurations (face to face, side by side, L-shaped, circular) and shows that these spatial arrangements aren't random but follow implicit rules that participants unconsciously respect, including how a group "leaves an opening" or, conversely, closes its circle completely.

For the cards: this gives a scientific basis to the intuitive sense that a group is "open" or "closed" to a new person joining. The circle's spatial openness is a real, studied, documented social signal, not just an impression.

Note: this link points to a figure illustrating the concept rather than the original work (1990, no freely accessible digital version).$$, 'https://www.researchgate.net/figure/Kendons-F-formation-system_fig1_261181296', true),

('a0000000-0000-0000-0000-000000000026', $$Écouter avant d'intervenir (pratique)$$, $$Listen before jumping in (practical)$$, $$Écouter avant d'intervenir$$, $$Listen before jumping in$$, $$Guide de communication en groupe$$, $$Group communication guide$$, null, null, null, $$Prendre quelques secondes pour capter le sujet en cours avant d'intervenir dans un groupe déjà engagé dans une conversation est une recommandation pratique courante en coaching de communication, cohérente avec le principe des F-formations de Kendon : le positionnement spatial et l'attention précèdent la prise de parole plutôt que l'inverse.$$, $$Taking a few seconds to catch the current topic before jumping into a group already engaged in conversation is a common practical recommendation in communication coaching, consistent with Kendon's F-formation principle: spatial positioning and attention come before speaking, not the other way around.$$, 'https://www.researchgate.net/figure/Kendons-F-formation-system_fig1_261181296', false),

('a0000000-0000-0000-0000-000000000027', $$Itzchakov & Kluger, 2017$$, $$Itzchakov & Kluger, 2017$$, $$I Am Aware of My Inconsistencies but Can Tolerate Them: The Effect of High-Quality Listening on Speakers' Attitude Ambivalence$$, $$I Am Aware of My Inconsistencies but Can Tolerate Them: The Effect of High-Quality Listening on Speakers' Attitude Ambivalence$$, $$Itzchakov, G., Kluger, A. N., & Castro, D. R.$$, $$Itzchakov, G., Kluger, A. N., & Castro, D. R.$$, 2017, $$Personality and Social Psychology Bulletin$$, $$Personality and Social Psychology Bulletin$$, $$À travers plusieurs expériences en laboratoire (dont une pré-enregistrée), les chercheurs ont manipulé la qualité d'écoute reçue par des participants pendant qu'ils exprimaient leurs opinions sur des sujets variés : un auditeur formé à une écoute empathique, attentive et non-jugeante d'un côté, un auditeur distrait ou plus évaluatif de l'autre. Les personnes ayant reçu une écoute de haute qualité se sont montrées moins défensives, ont rapporté moins de préoccupations sur l'image qu'elles donnaient, et ont exprimé un sentiment de connexion plus fort envers leur interlocuteur. Les chercheurs identifient trois composantes déterminantes de cette "écoute de qualité" : l'empathie, l'attention réelle portée au discours, et l'absence de jugement.

Pour les cartes : écouter n'est pas un acte passif sans effet. Ça change mesurablement l'état émotionnel et la perception de la personne qui parle, et améliore en retour la façon dont l'auditeur lui-même est perçu.$$, $$Across several lab experiments (including one preregistered), the researchers manipulated the quality of listening participants received while expressing their opinions on various topics: a listener trained in empathetic, attentive, non-judgmental listening on one side, a distracted or more evaluative listener on the other. People who received high-quality listening showed less defensiveness, reported fewer concerns about the image they were giving off, and expressed a stronger sense of connection to their conversation partner. The researchers identify three determining components of this "quality listening": empathy, real attention paid to what's said, and the absence of judgment.

For the cards: listening isn't a passive act with no effect. It measurably changes the emotional state and perception of the person speaking, and, in turn, improves how the listener themselves is perceived.$$, 'https://journals.sagepub.com/doi/10.1177/0146167216675339', true),

('a0000000-0000-0000-0000-000000000028', $$La technique du reflet (pratique)$$, $$The reflection technique (practical)$$, $$La technique du reflet$$, $$The reflection technique$$, $$Technique d'écoute active$$, $$Active listening technique$$, null, null, null, $$Reformuler brièvement ce qu'on vient d'entendre avant de répondre est une technique classique d'écoute active, cohérente avec les 3 composantes identifiées par Itzchakov & Kluger : elle force une attention réelle et communique explicitement à l'autre qu'il a été entendu.$$, $$Briefly rephrasing what you just heard before responding is a classic active-listening technique, consistent with the 3 components identified by Itzchakov & Kluger: it forces real attention and explicitly communicates to the other person that they were heard.$$, 'https://journals.sagepub.com/doi/10.1177/0146167216675339', false),

('a0000000-0000-0000-0000-000000000029', $$Eisenberger et al., 2003$$, $$Eisenberger et al., 2003$$, $$Does Rejection Hurt? An fMRI Study of Social Exclusion$$, $$Does Rejection Hurt? An fMRI Study of Social Exclusion$$, $$Eisenberger, N. I., Lieberman, M. D., & Williams, K. D.$$, $$Eisenberger, N. I., Lieberman, M. D., & Williams, K. D.$$, 2003, $$Science, 302$$, $$Science, 302$$, $$Les participants jouaient à un jeu de lancer de balle virtuel (Cyberball) pendant qu'ils étaient scannés en imagerie par résonance magnétique fonctionnelle (IRMf), le jeu étant manipulé pour qu'ils soient à un moment exclus par les deux autres joueurs (en réalité contrôlés par ordinateur). Résultat : l'exclusion active le cortex cingulaire antérieur (ACC), une zone cérébrale également impliquée dans le traitement de la douleur physique, et l'activation de cette zone est corrélée positivement avec la détresse rapportée par les participants. Les auteurs concluent que la douleur sociale suit des mécanismes cérébraux analogues à ceux de la douleur physique : une alarme qui signale une atteinte à un lien social important.

Pour les cartes : c'est l'argument scientifique central pour recadrer la souffrance liée au rejet social comme une réponse neurologique réelle et normale, pas comme une hypersensibilité personnelle à corriger.$$, $$Participants played a virtual ball-tossing game (Cyberball) while being scanned with functional magnetic resonance imaging (fMRI), with the game manipulated so that at some point they were excluded by the two other players (in reality controlled by computer). Result: exclusion activates the anterior cingulate cortex (ACC), a brain region also involved in processing physical pain, and activation in this region is positively correlated with the distress participants reported. The authors conclude that social pain follows brain mechanisms analogous to those of physical pain: an alarm that signals damage to an important social bond.

For the cards: this is the central scientific argument for reframing the suffering caused by social rejection as a real, normal neurological response, not a personal oversensitivity to fix.$$, 'https://www.science.org/doi/10.1126/science.1089134', true),

('a0000000-0000-0000-0000-000000000030', $$Reprendre contact (exposition)$$, $$Reconnecting (exposure)$$, $$Reprendre contact plutôt qu'éviter$$, $$Reconnecting rather than avoiding$$, $$Principe d'exposition (TCC)$$, $$Exposure principle (CBT)$$, null, null, null, $$Le principe qu'éviter systématiquement une situation redoutée entretient la peur associée, alors qu'une reconnexion progressive la réduit, est au cœur de la thérapie d'exposition en TCC et cohérent avec le modèle de Clark & Wells déjà mobilisé au cours 5, mais ce conseil précis (reprendre contact après un rejet) n'est pas lui-même issu d'un essai contrôlé cité dans ce document.$$, $$The principle that systematically avoiding a feared situation keeps the associated fear alive, while gradually reconnecting reduces it, is at the heart of exposure therapy in CBT and consistent with the Clark & Wells model already drawn on in course 5, but this specific piece of advice (reconnecting after a rejection) doesn't itself come from a controlled trial cited in this document.$$, 'https://www.science.org/doi/10.1126/science.1089134', false),

('a0000000-0000-0000-0000-000000000031', $$Granovetter, 1973$$, $$Granovetter, 1973$$, $$The Strength of Weak Ties$$, $$The Strength of Weak Ties$$, $$Granovetter, M. S.$$, $$Granovetter, M. S.$$, 1973, $$American Journal of Sociology, 78(6)$$, $$American Journal of Sociology, 78(6)$$, $$Granovetter a interrogé 282 hommes ayant récemment changé d'emploi dans la région de Boston sur la façon dont ils avaient obtenu l'information menant à leur nouveau poste. Résultat surprenant à l'époque : l'information la plus utile venait le plus souvent de "liens faibles", connaissances éloignées, contacts occasionnels, plutôt que de liens forts (famille, amis proches). L'explication théorique de Granovetter : les liens forts partagent déjà largement les mêmes informations et les mêmes cercles que soi (redondance), alors que les liens faibles donnent accès à des cercles sociaux différents et donc à des informations réellement nouvelles. Cette étude est devenue l'une des plus citées de toute la sociologie moderne, avec des applications qui dépassent largement le marché de l'emploi.

Pour les cartes : ça justifie de recadrer le réseautage professionnel non pas comme une performance sociale à optimiser en quantité, mais comme la construction, même minimale, de quelques liens légers réellement utiles.$$, $$Granovetter surveyed 282 men who had recently changed jobs in the Boston area about how they'd gotten the information that led to their new position. A surprising result at the time: the most useful information most often came from "weak ties," distant acquaintances, occasional contacts, rather than from strong ties (family, close friends). Granovetter's theoretical explanation: strong ties already largely share the same information and the same circles as you (redundancy), while weak ties give access to different social circles and therefore to genuinely new information. This study became one of the most cited in all of modern sociology, with applications that go well beyond the job market.

For the cards: this supports reframing professional networking not as a social performance to optimize by quantity, but as building, even minimally, a few genuinely useful light connections.$$, 'https://www.cs.cmu.edu/~jure/pub/papers/granovetter73ties.pdf', true),

('a0000000-0000-0000-0000-000000000032', $$Suivi périodique des liens faibles (pratique)$$, $$Periodic follow-up on weak ties (practical)$$, $$Le suivi périodique des liens faibles$$, $$Periodic follow-up on weak ties$$, $$Extrapolation pratique de Granovetter$$, $$Practical extrapolation from Granovetter$$, null, null, null, $$Puisque la valeur d'un lien faible vient de son existence même plutôt que de son intensité (Granovetter, 1973), l'entretenir avec un contact minimal mais périodique suffit à le maintenir actif. Ce conseil est une déduction pratique cohérente avec la théorie plutôt qu'un résultat mesuré isolément.$$, $$Since the value of a weak tie comes from its very existence rather than its intensity (Granovetter, 1973), maintaining it with minimal but periodic contact is enough to keep it active. This advice is a practical inference consistent with the theory rather than a result measured in isolation.$$, 'https://www.cs.cmu.edu/~jure/pub/papers/granovetter73ties.pdf', false),

('a0000000-0000-0000-0000-000000000033', $$Zhao & Epley, 2021$$, $$Zhao & Epley, 2021$$, $$Insufficiently Complimentary?: Underestimating the Positive Impact of Compliments Creates a Barrier to Expressing Them$$, $$Insufficiently Complimentary?: Underestimating the Positive Impact of Compliments Creates a Barrier to Expressing Them$$, $$Zhao, X., & Epley, N.$$, $$Zhao, X., & Epley, N.$$, 2021, $$Journal of Personality and Social Psychology$$, $$Journal of Personality and Social Psychology$$, $$Sur une série de neuf expériences, les chercheurs ont demandé à des participants de rédiger un compliment sincère destiné à quelqu'un, puis de prédire à quel point ce compliment rendrait la personne heureuse et à quel point ce serait gênant pour elle de le recevoir, avant de comparer ces prédictions aux réactions réelles des destinataires. Résultat constant : les personnes qui font le compliment sous-estiment systématiquement à quel point il rendra l'autre heureux, tout en surestimant à quel point ce sera gênant. Une étude compagnon montre en plus qu'un compliment répété à la même personne ne perd pas son impact positif dans la réalité, alors que les participants s'attendaient à un effet d'usure.

Pour les cartes : ça démontre que l'hésitation à complimenter repose sur une double erreur de prédiction, dans le sens qui décourage le plus d'agir. La peur que "ça devienne bizarre à force" ne se vérifie pas non plus dans les faits.$$, $$Across a series of nine experiments, the researchers had participants write a sincere compliment intended for someone, then predict how happy that compliment would make the person and how awkward it would be for them to receive it, before comparing these predictions to the recipients' actual reactions. Consistent result: people giving the compliment systematically underestimated how happy it would make the other person, while overestimating how awkward it would be. A companion study further shows that a compliment repeated to the same person doesn't actually lose its positive impact, even though participants expected a wearing-out effect.

For the cards: this demonstrates that hesitation to give compliments rests on a double prediction error, in the direction that most discourages acting. The fear that "it'll get weird after a while" also doesn't hold up in practice.$$, 'https://www.researchgate.net/publication/352138466_Insufficiently_Complimentary_Underestimating_the_Positive_Impact_of_Compliments_Creates_a_Barrier_to_Expressing_Them', true),

('a0000000-0000-0000-0000-000000000034', $$Dire le compliment sur le moment (pratique)$$, $$Saying the compliment in the moment (practical)$$, $$Dire le compliment sur le moment$$, $$Saying the compliment in the moment$$, $$Recommandation de bon sens$$, $$Common-sense recommendation$$, null, null, null, $$Formuler le compliment immédiatement plutôt que d'attendre réduit la fenêtre pendant laquelle l'hésitation peut s'installer et l'occasion se refermer. C'est cohérent avec le mécanisme identifié par Zhao & Epley : c'est l'anticipation de la gêne, pas la gêne réelle, qui bloque le passage à l'action.$$, $$Giving the compliment immediately rather than waiting shortens the window during which hesitation can set in and the opportunity can close. This is consistent with the mechanism identified by Zhao & Epley: it's the anticipation of awkwardness, not actual awkwardness, that blocks taking action.$$, 'https://www.researchgate.net/publication/352138466_Insufficiently_Complimentary_Underestimating_the_Positive_Impact_of_Compliments_Creates_a_Barrier_to_Expressing_Them', false)
on conflict (id) do update set short_label = excluded.short_label, short_label_en = excluded.short_label_en, study_title = excluded.study_title, study_title_en = excluded.study_title_en, authors = excluded.authors, authors_en = excluded.authors_en, year = excluded.year, journal_or_publisher = excluded.journal_or_publisher, journal_or_publisher_en = excluded.journal_or_publisher_en, summary = excluded.summary, summary_en = excluded.summary_en, external_url = excluded.external_url, is_scientific = excluded.is_scientific;
